USE [Log]
GO

/****** Object:  Table [dbo].[Lockers]    Script Date: 11/10/2016 12:41:43 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[Lockers](
	[LockerId] [int] NOT NULL,
	[CardId] [nvarchar](50) NOT NULL,
	[Busy]   [BIT] NOT NULL
 CONSTRAINT [PK_Lockers] PRIMARY KEY CLUSTERED 
(
	[LockerId] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
) ON [PRIMARY]

GO


