USE [Log]
GO


SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[ModelInformations]
(
	[Version] [nvarchar](50) NOT NULL,
	[Date] [nvarchar](10) NOT NULL,
	[Time] [nvarchar](8) NOT NULL,

	CONSTRAINT [PK_ModelInformations] PRIMARY KEY CLUSTERED 
	(
		[Version] ASC
	)
	WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]

) 

ON [PRIMARY]

GO


